services:
  db:
    container_name: ${DB_CONTAINER_NAME}
    image: postgres:18
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - ${DB_EXTERNAL_PORT}:${DB_INTERNAL_PORT}
    env_file:
      - .env
  backend:
    container_name: ${API_CONTAINER_NAME}
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DB_URL}
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: 'pnpm run api:dev'

  frontend:
    container_name: ${VUE_CONTAINER_NAME}
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - ${VUE_EXTERNAL_PORT}:${VUE_INTERNAL_PORT}
    env_file:
      - .env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: 'pnpm run dev --host --port ${VUE_INTERNAL_PORT}'

volumes:
  postgres_data: